spring:
  datasource:
    url: jdbc:mysql://10.22.59.181:3306/employee_db?useSSL=false
    username: admin
    password: ENC(vbRvfzRZhtJ2F5k45+R12EvMIyiVeha6)
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 1000
      max-lifetime: 1000
      auto-commit: false
#  security:
#    user:
#      name: rama
#      password: pass123

  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
server:
  port: 8082




