INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
			      VALUES (1, "Solution-OFSD", "Vinod B",1,now() ,1,now());
 INSERT INTO department (DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
			      VALUES (2, "Solution-AMS", "Vinod B",1,now(),1,now());

 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (1, "US",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (2, "Canada",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (3, "ME",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (4, "Europe",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (5, "Africa",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (6, "ASEAN",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (7, "India",1,now(),1,now());
 INSERT INTO region (REGION_ID,REGION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (8, "ANZ",1,now(),1,now());

 INSERT INTO location (LOCATION_ID,LOCATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (1, "Mumbai",1,now(),1,now());
 INSERT INTO location (LOCATION_ID,LOCATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (2, "Chennai",1,now(),1,now());

INSERT INTO skill (SKILL_ID,SKILL_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (1, "Java",1,now(),1,now());
 INSERT INTO skill (SKILL_ID,SKILL_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (2, ".Net",1,now(),1,now());

INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (1, "PROJECT LEADER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (2, "SR. PROJECT MANAGER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (3, "ASSOCIATE VICE PRESIDENT-PROJECTS",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (4, "TEST LEAD",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (5, "SR. MANAGER-OTS",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (6, "SR. TEAM LEADER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (7, "ASST. MANAGER-OTS",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (8, "ASST.TEST MANAGER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (9, "ASST.MANAGER-RECON",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (10, "ASSOCIATE VICE PRESIDENT-OTS",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (11, "ASST.PROJECT MANAGER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (12, "SR. PROJECT ASSOCIATE",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (13, "SENIOR TEST LEAD",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (14, "PROJECT MANAGER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (15, "ASSISTANT VICE PRESIDENT-SOLUTIONS",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (16, "TESTING ENGINEER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (17, "ASSISTANT PROJECT MANAGER",1,now(),1,now());
 INSERT INTO designation (DESIGNATION_ID,DESIGNATION_NAME,INS_USER,INS_DATE,LAST_UPDATE_USER,LAST_UPDATE_DATE)
  VALUES (18, "TEST MANAGER",1,now(),1,now());

INSERT INTO user (USER_SQID,USER_ID,USER_NAME,EMAIL,PASSWORD,INS_DATE,LAST_UPDATE_DATE)
  VALUES (1, 1,"rakeshm","rakeshm@fss.co.in","pass@123",'2020-04-08 10:10:10','2020-04-08 10:10:10');

 INSERT INTO service_line (SERVICE_LINE_ID,SERVICE_LINE_NAME)
  VALUES (1, "Engineering");
 INSERT INTO service_line (SERVICE_LINE_ID,SERVICE_LINE_NAME)
  VALUES (2, "Testing");
 INSERT INTO service_line (SERVICE_LINE_ID,SERVICE_LINE_NAME)
  VALUES (3, "Switching");
 INSERT INTO service_line (SERVICE_LINE_ID,SERVICE_LINE_NAME)
  VALUES (4, "Portfolia Management Services");

 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (1, "EARMARKED");
 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (2, "MANAGEMENT");
 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (3, "BENCH");
 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (4, "MATERNITY LEAVE");
 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (5, "LOAN");
 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (6, "REPLACEMENT");
 INSERT INTO billable_status (BILLABLE_STATUS_ID,BILLABLE_STATUS)
  VALUES (7, "BILLABLE");

INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (1, "M1");
 INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (2, "M2");
 INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (3, "M3");
 INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (4, "M4");
 INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (5, "M5");
 INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (6, "M6");
 INSERT INTO grade (GRADE_ID,GRADE_NAME)
  VALUES (7, "M7");

  INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (1, "BSC");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (2, "MSC");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (3, "BSCIT");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (4, "MSC IT");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (5, "BCA");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (6, "MCA");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (7, "BTECH");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (8, "MTECH");
 INSERT INTO academics (ACADEMICS_ID,ACADEMICS_NAME)
  VALUES (9, "MBA");

 INSERT INTO project_tagging (PROJECT_TAGGING_ID,PROJECT_TAGGING)
  VALUES (1, "Reserved");
 INSERT INTO project_tagging (PROJECT_TAGGING_ID,PROJECT_TAGGING)
  VALUES (2, "OnBoarding");
 INSERT INTO project_tagging (PROJECT_TAGGING_ID,PROJECT_TAGGING)
  VALUES (3, "Execution");

 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (1, "Project Manager");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (2, "Program Manager");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (3, "Technical Architect");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (4, "Payment Application SME");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (5, "Development Engineer");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (6, "Implementation Engineer");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (7, "Golden Gate/Prognosis");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (8, "L1 Support Engineers");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (9, "L2 Support Engineers");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (10, "Database Administrator");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (11, "Middleware Administrator");
 INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (12, "System Administrator");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (13, "Business Analyst");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (14, "Solution Architect");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (15, "Automation Engineer (RPA)");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (16, "Database Developer");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (17, "Java Developer");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (18, "Mobile Developer");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (19, "Functional Tester");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (20, "Automation Tester");
INSERT INTO role (ROLE_ID,ROLE_NAME)
  VALUES (21, "Non Functional Tester");